### PR TITLE
Switch order of self-host and oasis on /get

### PR DESCRIPTION
**Pull request by neynah**
Ready for review.

- Moved self-hosting section to be above managed hosting
- Switched the order of self-host & managed hosting titles and icons (just below the banner)

Also slight string improvements:
- Changed "Start using Sandstorm right away and share with friends for free" to "Start using Sandstorm for free right away and collaborate with others"
- Organizations: Changed "Start a Free Trial" to "Start a Free 90-day Trial"
- Under Hosted Service section: Changed "Start for Free" to "Start on Oasis for Free"

### CODE REVIEW

**Comment by kentonv** [comment]
We're probably going to shorten the trials to 60 days. Maybe best not to add "90-day" for now since there's a risk we'll forget to update it?

**Comment by neynah** [comment]
> We're probably going to shorten the trials to 60 days. Maybe best not to add "90-day" for now since there's a risk we'll forget to update it?

Good point. OK, I reversed that change.

**Comment by neynah** [comment]
Also, our docs currently say [90-day](https://docs.sandstorm.io/en/latest/administering/for-work/) trials so we should remember to update that too.

**Comment by paulproteus** [comment]
On /get

> Questions? E-mail us

This has an HREF to oasis, but maybe should have a HREF to a mailto: link. contact@ perhaps?

> Storage is up to you!

I would shrink this text so it's the same as "Unlimited grains", in the two "cards" for "Individual" and "Organizations", but that's unrelated to this PR. Not a showstopper.

> Unlimited grains

This page uses the phrase "Unlimited grains" within the two "cards" for self-hosted. That's unrelated to this PR, but interestingly we haven't defined the word "grains" here yet. That might be a reason to omit the line entirely from the self-hosting cards. Not at showstopper.

Beyond that, +1

**Comment by paulproteus** [comment]
I also think our UI for "tabs" in "Self-host" vs. "Managed Hosting" is difficult to understand (compare http://getbootstrap.com/components/#nav-pills to what we do at the top of /get ). Not a showstopper - not new in this PR - but I figured I might as well comment on it.

**Comment by paulproteus** [comment]
While I'm commenting on this page, this text:

- Individual
    - Sandstorm is open source and runs on any Linux x86-64 server. Free dynamic DNS & SSL certificates.

IMHO we should s/Individual/Standard/ , just like in the admin onboarding wizard.

- For Work
    - Sandstorm for Work adds features and integrations that businesses need. Comes with SAML & LDAP.

IMHO we should state that this includes everything in Standard. However, when I fiddle with wordings for that, I can't make it fit on two lines, so maybe there's no way to state that. So maybe ignore this train of thought.

**Comment by paulproteus** [comment]
"Sandstorm for Work" here is also missing the "Upgrade at any time" text, which answers a FAQ that people seem to have. Oh well.

**Comment by paulproteus** [comment]
@neynah I see that there's now a revised commit fixing the missing email address, addressing the only important issue I have with this. +1 for its merge.

**Comment by neynah** [comment]
>This has an HREF to oasis, but maybe should have a HREF to a mailto: link. contact@ perhaps?

Yikes. Fixed.

> I would shrink this text so it's the same as "Unlimited grains", in the two "cards" for "Individual" and "Organizations", but that's unrelated to this PR. Not a showstopper.

The font-size is consistent with the storage font-size in the Oasis cards. I think we want to emphasize storage over grains on all cards so I'd rather keep them consistent.

>This page uses the phrase "Unlimited grains" within the two "cards" for self-hosted. That's unrelated to this PR, but interestingly we haven't defined the word "grains" here yet. That might be a reason to omit the line entirely from the self-hosting cards. Not at showstopper.

Yeah we should define grains. I will open an issue for that shortly.

>I also think our UI for "tabs" in "Self-host" vs. "Managed Hosting" is difficult to understand (compare http://getbootstrap.com/components/#nav-pills to what we do at the top of /get ). Not a showstopper - not new in this PR - but I figured I might as well comment on it.

I don't think our current UI is perfect but using nav pills would give the impression that the content will be found on a different tab/page. Clicking on a nav pill and having it scroll down will be sort of strange especially when one of those pills becomes active- if the user clicks on "managed-hosting" pill then scrolls back up does the "self-host" pill then become active?

Having said that, maybe we should consider putting oasis managed hosting & self-host on different tabbed pages. Each with real estate mentioning the existence of the other option (e.g. self-host vs managed hosting).

>IMHO we should s/Individual/Standard/ , just like in the admin onboarding wizard.

Yeah I think this consistency is important. Fixed.

> "Sandstorm for Work" here is also missing the "Upgrade at any time" text, which answers a FAQ that people seem to have. Oh well.

I'd be +1 on including "Upgrade at any time" but on this page it's currently unclear that there are different pricing options other than $15/user/month. Perhaps you mean that there is flexibility in the number of users you can have/pay for?

**Comment by paulproteus** [comment]
> The font-size is consistent with the storage font-size in the Oasis cards. I think we want to emphasize storage over grains on all cards so I'd rather keep them consistent.

OK, but I want you to try de-emphasizing it for just a second locally, and see what I saw - that the large text about yelling detracts from the call to action button of install/start-free-trial.

I'm OK with whatever outcome on this, but I do want you to see what I saw.

> I'd be +1 on including "Upgrade at any time" but on this page it's currently unclear that there are different pricing options other than $15/user/month. Perhaps you mean that there is flexibility in the number of users you can have/pay for?

I mean upgrade from Standard to For Work at any time.

> Having said that, maybe we should consider putting oasis managed hosting & self-host on different tabbed pages. Each with real estate mentioning the existence of the other option (e.g. self-host vs managed hosting).

+0.5 on this. I guess we'd redirect `/get` to `/get/self-host` or something like that, to avoid breaking old links?

Anyway I'm +1 in general; this is just discussion which you an feel free to cut short whenever.

**Comment by kentonv** [comment]
@paulproteus Is this ready to merge? I think you are saying so but can't completely tell.

**Comment by paulproteus** [comment]
+1 ready to merge.

**Pull request merged**
