### PR TITLE
Added Paperwork to Sandstorm App List

### PR DESCRIPTION
**Pull request by JamborJan**

### CODE REVIEW

**Comment by kentonv** [comment]
Hmm, why target=_blank? None of our other links have that.

**Comment by JamborJan** [comment]
Because I hate it when links open on the page where I am and not in a new tab.

Especially in this use case: you browse the app list and want to check quickly the links. You click one check the github profile and you close the tab to go back to continue browsing or install the app. It's a pain when you have to go back and reload the page especially when you visited some more links and have to go back, back, back.

You can say it's user experience. Thats why I did it.

**Comment by kentonv** [comment]
Hey Jan,

If you as a user want links to open in a new tab, you should ctrl+click them. Some users do not want a new tab -- opening a new tab can disrupt browsing because now the user can't just click back, they have to go close the tab. Setting target=_blank, though, forces everyone to open new tabs whether they want to or not.

It's also bad to have some links on the page use target=_blank while others do not, since it creates an inconsistent experience for users who are going through the whole list clicking links.

So I don't think we should use target=_blank on these links.

**Comment by JamborJan** [comment]
Despite the fact that I cannot ctrl+click on a mobile device and that maybe 80% of the user for whom we are building this platform - non tech user who simply want to use things - don't know that ctrl+click exists, I will change it. It's your website / app list. But I think differently :-)

**Comment by JamborJan** [comment]
I removed the target=_blank. Anything else not okay with the listing?

JJ

**Comment by kentonv** [comment]
Hey Jan,

After merging this I found that the hash (package ID) doesn't match. I will fix that, but just as a reminder, be sure that the package content at the URL you gave doesn't change -- if there's a new version, be sure to put it at a new URL so we can keep the hash and URL synchronized.

I also feel like the description is too heavy on technical details while the reader is probably more interested in features. I notice that several of our descriptions have this problem, so I'm going to go through and fix some of them.

Should be up in an hour or two.

Thanks!

**Comment by JamborJan** [comment]
Package id is odd because I downloaded it and did 'echo `sha256sum paperwork.spk | head -c 32' as Jason told me.

I absolutely agree with the description. I aligned my wording with the others despite the fact that it should be more user friendly where a user is not a tech person.

**Pull request merged**
