### PR TITLE
Add blog post offering publicity to app authors

### PR DESCRIPTION
**Pull request by paulproteus**

### CODE REVIEW

**Comment by paulproteus** [comment]
@kentonv ready for your merge/review. Sorry about the delay.

**Comment by paulproteus** [comment]
@simonv3 if you are willing to read the blog post <https://github.com/paulproteus/sandstorm-website/blob/add-asheesh-new-blog-post/_posts/2016-02-05-app-author-publicity-oasis.md> and +1 -1 it, since I quote you, that'd be nice.

**Comment by simonv3** [comment]
+1 looks good to me!

**Comment by paulproteus** [comment]
Thanks!​

**Pull request merged**
