### PR TITLE
Graphic for decentralize storage blog post

### PR DESCRIPTION
**Pull request by neynah**
I can make fixes tonight if we want to publish the blog post tomorrow. :)

### CODE REVIEW

**Comment by kentonv** [comment]
Hmm, can we use a more diverse set of Sandstorm app icons?

Also can we have some sort of indication that we're trying to move from the left to the right? (Maybe just an arrow, unless you have better ideas.)

I think we'll probably shoot for Wednesday for publishing.

**Comment by neynah** [comment]
>Hmm, can we use a more diverse set of Sandstorm app icons?

OK, I updated the graphic. Let me know if that's enough variety.

> Also can we have some sort of indication that we're trying to move from the left to the right? (Maybe just an arrow, unless you have better ideas.)

I think using an arrow is the clearest.

**Comment by paulproteus** [comment]
For what it's worth, on the Sandstorm right-hand-side, it's hard to tell you're connecting the _apps to people_ rather than _apps to apps_. I think the point is that you're connecting apps to people; if so, maybe there's a way to make that visually more clear. If not, oh well, that's life.

**Comment by kentonv** [comment]
@neynah Hmm, I was thinking, what if we desaturate the left side a bit? Will make the right side look more friendly in comparison. :)

I also feel like reducing the number of people clustered around the apps on the left deflates the message somewhat. I actually feel like there should be a very large number of small people... emphasizes that these centralized apps are huge and the people using them are relatively powerless. Thoughts?

@paulproteus It's actually supposed to show both kinds of connections.

**Comment by paulproteus** [comment]
> It's actually supposed to show both kinds of connections.

What does a user-to-user connection mean in the context of this diagram? Is there a reason that user-to-user connections aren't shown on the diagram to the left, then?

> I actually feel like there should be a very large number of small people... emphasizes that these centralized apps are huge and the people using them are relatively powerless.

FWIW, I think having lots of people on the left makes those apps look appealingly popular and makes our userbase look insignificant and implies our use-case is fringe.

Neither of the above is intended to be a blocker; just my opinions.

**Comment by neynah** [comment]
> What does a user-to-user connection mean in the context of this diagram? Is there a reason that user-to-user connections aren't shown on the diagram to the left, then?

@paulproteus There are user-to-user connections on the left as well.

@kentonv I have 2 versions here for comparison:
decentralize-storagev2

decentralize-storagev2 1

I think I prefer the 2nd one with smaller people; it does make them seem less significant.

**Comment by neynah** [comment]
I updated this commit to have the 2nd graphic displayed in my previous comment. Let me know if there are more changes.

**Comment by kentonv** [comment]
For the left side, maybe all the people should have lines to the apps, but not each other?

**Comment by neynah** [comment]
Okay, updated.

decentralize-storage

**Pull request merged**
