### PR TITLE
Play "Darude - Sandstorm" when Konami code is entered

### PR DESCRIPTION
**Pull request by jomo**
When you enter the [konami code](http://knowyourmeme.com/memes/konami-code#fnr2) on your keyboard, the song [Darude - Sandstorm](http://knowyourmeme.com/memes/darude-sandstorm#fnr3) starts to play via a hidden YouTube iframe.

A [lot of websites](http://konamicodesites.com/) use the konami code for easter eggs.

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
I suddenly wonder why it took someone so long to suggest this.

**Comment by kentonv** [comment]
Award for most entertaining pull request I've received. :)

Sadly I'm not sure if we can actually pull this. I hate to be a killjoy but I think this would qualify as copyright infringement -- even though we're not serving the music, we would be using it for what could reasonably be described as "marketing" while hiding their own youtube ads. I believe it would be a Youtube TOS violation as well. Now that we have seed funding we unfortunately have to cover our asses on these things.

I wonder if we can come up with some other easter egg, though? As a gamer I do love the idea of using the konami code. :)

**Comment by jomo** [comment]
I think it should be fine. The song is licensed under the "Standard YouTube License" which is pretty much [YouTube's ToS](https://www.youtube.com/t/terms?gl=US):

> You agree not to use the Service for [...] the sale of advertising, sponsorships, or promotions on any page of an ad-enabled blog or website containing Content delivered via the Service, **unless other material not obtained from YouTube appears on the same page** and is of sufficient value to be the basis for such sales.

(i.e. they [don't want](https://support.google.com/youtube/answer/71011?hl=en) you to put up a page with ads showing only a youtube video)

**Comment by kentonv** [comment]
Hi jomo,

Sorry but I don't think that's true. Section 4F of the YouTube TOS says:

>If you use the Embeddable Player on your website, you may not modify, build upon, or block any portion or functionality of the Embeddable Player, including but not limited to links back to the YouTube website.

Placing the video in an invisible iframe surely violates this -- we'd be "blocking" the ads and links.

**Comment by jomo** [comment]
hmm I see

**Comment by jomo** [comment]
See my last commit.
I found out that the Internet Archive hosts the song as well, and as far as I know, they don't have any issues with embedding their files.
It's also audio only instead of a hidden video :+1:

**Comment by kentonv** [comment]
I'm sorry, @jomo, but this doesn't solve the problem. The copyright is ultimately owned by Darude, not the Internet Archive nor YouTube. With YouTube, we know that Darude has published the work under YouTube's terms, and therefore we'd just need to follow YouTube's terms ourselves. With archive.org, it looks like the files were uploaded without permission from Darude, so it doesn't matter if archive.org is OK with it. Moreover, the default assumption with copyrights is that all rights are reserved, so "as far as I know they don't have any issues" is not good enough.

There's another problem, which I didn't bring up earlier because it's a matter of opinion while the copyright issue is fact, but to be honest I don't like the song very much and would rather not associated it with our brand. Sorry for being a killjoy. :/

**Comment by jomo** [comment]
Oh well, at least I tried :sunglasses: 

by the way, I didn't add the song because I particularly like it but rather because it's just iconic (and because it's called sandstorm, ofc).

----

I guess this isn't going to be merged then. Feel free to do something fancy with the konami code stuff if you like.

**Pull request closed without merging**
