### PR TITLE
Add HackerSlides

### PR DESCRIPTION
**Pull request by jacksingleton**
https://github.com/jacksingleton/hacker-slides

A simple app that combines Ace Editor and RevealJS. You can write markdown on the left, and preview your presentation on the right.

I put this together pretty quickly because I could not find an open source web based presentation app. It still needs some work, but is functional!

Let me know if you have any feedback.

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
It doesn't like anyone has permission to access the SPK file.

**Comment by kentonv** [comment]
Whoa, nice!

It looks like your AWS URL is not public-accessible, so I haven't been able to try the actual app yet, but just based on the screenshot I'm pretty excited. Please let me know when you've corrected the permissions.

Looking at your code, it looks like your server-side is just a short Python server that serves static content and a GET/PUT interface for the slides text. I think you could easily replace this with something based on [sandstorm-rawapi-example](https://github.com/sandstorm-io/sandstorm-rawapi-example) -- you probably wouldn't need to make any changes to its code. The advantage of this is that your package will be smaller, your app will start up faster, and your app will use _much_ less RAM (which means it will use fewer [compute units](https://blog.sandstorm.io/news/2015-01-14-compute-units.html) on our managed hosting).

That said, no need to make that change for the first release.

**Comment by kentonv** [comment]
Oh, if you'd like a t-shirt, please send your shipping address and shirt size to jade@sandstorm.io. :)

**Comment by jacksingleton** [comment]
Oops should be public now.

**Comment by jacksingleton** [comment]
Cool, I'll give the raw api a try next. The server is super simple.

Please add issues if you find bugs! I haven't tested it a ton but wanted to get something functional out there.

Wohoo t-shirt!

**Comment by kentonv** [comment]
If you want to add a ["try it on Sandstorm"](https://blog.sandstorm.io/news/2015-02-06-app-demo.html) button to your github readme (or anywhere else), here's the link to use:
https://demo.sandstorm.io/appdemo/7qvcjh7gk0rzdx1s3c8gufd288sesf6vvdt297756xcv4q8xxvhh

And you can find button images to use here:
https://github.com/sandstorm-io/sandstorm-website/tree/master/logos

**Comment by kentonv** [comment]
Another thing that will be a problem eventually is that "present" mode opens a new window directly rendering content from the session host. The problem is that if the user closes the Sandstorm tab, browses away from the app in Sandstorm, or even refreshes Sandstorm, the session will end and the session host will no longer be valid. Also, eventually we'll disallow apps from opening new windows.

With that said, I don't think there's a good alternative at the moment. I was going to suggest using the web publishing functionality, but that would make the slides public, which isn't quite right. I think what we probably want to do is create a way by which apps can request full-screen display. I think this just requires sticking an attribute on the iframe, except that I'm not quite sure if we want to allow all apps to go full-screen or if there should be some sort of permission check implemented by Sandstorm. Hmm.

Anyway, for now, no action required.

**Comment by ocdtrekkie** [comment]
I am tempted to almost suggest full screen just be an option on the Sandstorm command bar. Rather  than let apps request it, just let users control it. Given the fact that in a sufficiently app-rich ecosystem, Sandstorm could essentially be a virtual desktop of sorts, it wouldn't be awful to have the option to hide your non-Sandstorm UI. :)

Potentially, you could keep the Sandstorm bar in full screen, even, but have it auto-hide unless you move your cursor and go up to it or something.

**Comment by kentonv** [comment]
> I am tempted to almost suggest full screen just be an option on the Sandstorm command bar.

Actually, I like that.

One problem is that many apps want to display differently in full-screen. E.g. a video player may appear in a box with UI around it normally, but in full-screen you want the video covering the whole screen. Hacker Slides is another example. It would be sad if people have to click "full screen" in two different places -- once in the app and once outside.

Perhaps a solution is for Sandstorm to tell the app when it is full-screened so that it can display in the appropriate form factor without the user clicking another thing in-app. So apps wouldn't have their own internal full-screen control at all.

**Comment by ocdtrekkie** [comment]
That sounds reasonable. I could see some merit in letting the app also request the ability to fullscreen from it's side for certain design flows. But yeah, in one direction or the other it's probably ideal to allow the API to communicate that so you never have to click twice for one action.

**Pull request merged**
