### PR TITLE
WIP: replace twitter with fediverse account.

### PR DESCRIPTION
**Pull request by zenhack**
This doesn't currently change the logos, which appear to be part of an icon font. Figuring out how to modify those is a bit more than I bargained for right now, so committing this and submitting it as a draft.

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
@zenhack Do you prefer the AP logo to be entirely purple? I figured the pink still fit our brand colors well enough we could keep that bit.

**Comment by ocdtrekkie** [comment]
The online demo button on the home page is a very similar pink, so I think we could keep it dual color but in Sandstorm colors.

**Comment by zenhack** [comment]
Ah, already made the change before I saw your comment. I think having it not monochrome would look weird given that all the other icons are, though in isolation I wouldn't necessarily have a problem.

Anyway, i think this is ready to go.

**Review by ocdtrekkie — APPROVED** [review]
It looks like a slightly different shade of purple, but I'm not sure that's really noticeable to the average person. All three places I know it appears looks good to me.

**Comment by zenhack** [comment]
It shouldn't be, I pulled the hex code out of one of the other svgs. Anyway, merging.

**Pull request merged**
