### PR TITLE
Add donation bar below nav and above footer

### PR DESCRIPTION
**Pull request by neynah**
For @zarvox! 

Below nav on every page:

image

Above footer on every page:

image

Mobile:

image

### CODE REVIEW

**Comment by zarvox** [comment]
Iterating on this in-person.

**Comment by ocdtrekkie** [comment]
This is cool, I'm excited to be able to potentially send you guys more dollars without having to figure out what to buy that I don't really need. Will this show up on "Work"/"Enterprise" related pages too? That would seem odd. Donating to Sandstorm-the-Open-Source-Project seems quite worthwhile, but people may feel like they're being asked to donate to Sandstorm-the-Company.

**Comment by kentonv** [comment]
I think if we do this we need to message it carefully. E.g. it's weird to go to /get and see both "donate" and "buy things from us". The "donate" cue could turn off enterprise customers. Meanwhile conversely the "buy things" cue turns off "indie" enthusiasts who might otherwise donate (we've actually heard people tell us that they initially ignored Sandstorm because it seemed "not indie" with the pricing options).

**Comment by neynah** [comment]
We'll be implementing these changes as an A/B test.

These new colours make me cringe (in terms of cohesion with the overall colour scheme of the website) but we want to make this banner as noticeable as possible.

image

image

image

image

Also:
- Fixed link on /get so that it goes to /install instead of https://sandstorm.io/install
- Reduced size of "Contact" call-to-action at the bottom of /get so it's not so massive on mobile

image

**Comment by paulproteus** [comment]
looks :guava: to me

**Pull request merged**
