### PR TITLE
List fixes and Blocks info

### PR DESCRIPTION
**Pull request by ocdtrekkie**
Missing line break in IPython listing was quirky. And we had some amp;s and some ands and an amp; with no spaces around it. The inconsistency made me sad.

And while I doubt I'll update Blocks further unless I need to update compatibility with the platform, as it's pretty complete, I like having dates and versions, and now that other apps have it, I am adding my details.

### CODE REVIEW

**Comment by kentonv** [comment]
The "amp;"s should be "&amp;", shouldn't they?

I think the non-spacing in one case was intentional to avoid a line wrap, though the whole format may have changed since then.

**Comment by ocdtrekkie** [comment]
Yes. I haven't HTML'd things in way too long. >.< Should be fixed and I found an "and" I missed in the Google Wave listing.

I think the format might have changed, since the current one is pretty stretchy. But I can say it drives me up a wall either way.

**Comment by ocdtrekkie** [comment]
As a note, there are three instances, including the one aforementioned potential line wrap avoidance, where the second author's name is cut onto a new line. My inclination, since only the one of the three could stay on the same line by squishing spaces, would be to use a `<nobr>` tag around the second author's name so that the name went to the second line intact. However, apparently that is deprecated, and the proper answer would be a CSS class: http://davidwalsh.name/nobr-css (I have a pet peeve about short, useful HTML codes being deprecated for clunky, annoying CSS bits, but if we're being compliant, there it is.)

**Comment by kentonv** [comment]
I agree that wrapping in the middle of a name is sad.

Googling `nobr` suggests to me that it is not just "deprecated" but was never a standard in the first place. I dunno. In any case, what you want here is `<span class="nobr">`, then define `.nobr` in the CSS.

Another solution could be to just replace the space in their name with `&nbsp;`, although that might be weird if someone tries to copy/paste the name.

**Comment by ocdtrekkie** [comment]
.nobr is implemented as per the link in my above comment, and it has been placed around instances where contributors names were cut in half, which forced them to move to the new line entirely instead.

**Comment by kentonv** [comment]
Looks good, thanks!

**Pull request merged**
