### PR TITLE
Add Let's Chat

### PR DESCRIPTION
**Pull request by jparyani**
This is waiting on https://github.com/kentonv/node-capnp/pull/17. Without it, some forms such as changing profile settings, do not work.

### CODE REVIEW

**Comment by kentonv** [comment]
Sorry, I have a nitpick: When I open the grain anonymously, it just says "unauthorized". Could we make it say: "To join the chat, please sign in!"

Sorry I didn't catch this earlier.

**Comment by jparyani** [comment]
Fixed

**Comment by jparyani** [comment]
Fixed for real this time

**Comment by jparyani** [comment]
Fixed chat history bug

**Pull request merged**
