### PR TITLE
Front page styling and screenshots

### PR DESCRIPTION
**Pull request by neynah**
Not ready to merge yet. Will wrap it up tonight. Happy to make changes to the screenshots. :)

### CODE REVIEW

**Comment by paulproteus** [comment]
Where are these person images coming from? If these are real people's images, then it's best to make sure they're OK with us using their personal images on our website to promote Sandstorm, even if the images have copyright licensing that is permissive enough to allow us to use them.

If you have any questions about that, feel free to ask me off-thread or on-thread.

One option is to use cartoons, since there's no personal publicity issue with those. Some public domain cartoon faces can be found at:

- https://openclipart.org/search/?query=cartoon%20face

I particularly like https://openclipart.org/detail/6131/face-1-colour , personally. However, in a quick search, I couldn't find anything else I liked as much as that, nor anything else in the same style, and it'd be good to have the various person images be consistent in style.

In theory Wikimedia Commons is another good source, e.g.

- https://commons.wikimedia.org/w/index.php?title=Category:Cartoon_characters&filefrom=%E0%B8%82%E0%B8%99%E0%B8%A1%E0%B8%AB%E0%B8%A7%E0%B8%B2%E0%B8%99.jpg#mw-category-media

Another approach is to use people's heads who work at Sandstorm. I think that's a pretty nice way to do things personally; perhaps Jade's and David's head. Or mine, if you want it.

**Comment by neynah** [comment]
> Where are these person images coming from? If these are real people's images, then it's best to make sure they're OK with us using their personal images on our website to promote Sandstorm, even if the images have copyright licensing that is permissive enough to allow us to use them.

They're all creative commons images that allow modification without attribution. Honestly, I think we should either use these images(or other creative commons images) or pay for stock images. We can get up to 10 free ones to start with Adobe Stock. Using our own images diminishes the "credibility" or "authenticity" of the use-cases we are presenting. I would hesitate to use our own employees as examples of customers.

**Comment by paulproteus** [comment]
I vote that we use Adobe Stock images in that case! I wish I could suggest CC in this case, but I think I can't, so there you go. I'd like to see a note in the commit log message for these screenshots that they use the Adobe Stock images, and preferably I'd also like to see a new folder created in the `sandstorm-website` repo called `from-adobe-stock` or something like that, so long as it's OK to distribute the original Adobe Stock images like that, so that any Sandstorm person can use these images while setting up their own demo environment for taking screenshots like you have been. I know that's a bunch of work to request from you.

Rationale for not using CC images: https://wiki.creativecommons.org/wiki/Chang_v._Virgin_Mobile (I happen to remember parts of that lawsuit unfolding while I was at Creative Commons)

**Comment by neynah** [comment]
Yeah, good call. I'll swap in Adobe Stock photos tonight. Thanks for advice. It's more work but its

**Comment by neynah** [comment]
..work that's important. (Github on mobile is pretty janky)

**Comment by neynah** [comment]
Swapped out images for Adobe Stock ones.

>"...you may not distribute the digital asset by posting it online or in any other way that would let other people use the asset without licensing it themselves." https://stock.adobe.com/license-terms#

Unfortunately, we can't include the assets in the repo. But I will make a note of the Adobe Stock image IDs used: 84476470, 102948208, 110893136.

**Comment by neynah** [comment]
I've also reduced the height of the top banner a smidge and adjusted the font-sizes to look better.

**Comment by ocdtrekkie** [comment]
Is that statement indicate some requirement the site itself have some sort of DRM to prevent people from lifting the image?

**Comment by neynah** [comment]
@ocdtrekkie the images have been altered and they're much too small to be usable as they only make up small parts of the screenshots. There are some terms specific to how much of the image can be made of the original asset. 

In any case don't merge this yet. I will read the full licensing terms tonight once I'm done flying.

**Comment by neynah** [comment]
I found the relevant terms for Enterprise use:
image
image
image

Full text here: http://wwwimages.adobe.com/content/dam/acom/en/legal/terms/enterprise/pdfs/PSLT-Stock_NA_2015v2-2.pdf

**Comment by paulproteus** [comment]
@neynah I notice on my laptop that the screenshots would benefit from having "2x" aka "retina" versions. Let me know if I should say more, and/or if you considered this and decided it wasn't important for now.

ToS seem fine to me.

**Comment by neynah** [comment]
@paulproteus Yes, I have larger versions I can put in a future PR this week(probably today).

**Pull request merged**
