### PR TITLE
New blog post about Giftr

### PR DESCRIPTION
**Pull request by neynah**

### CODE REVIEW

**Comment by paulproteus** [comment]
I presume the action requested here is review/merge by Kenton, so I'll let
him do that. If you need any action from me, feel free to ping & request it.

**Comment by neynah** [comment]
@kentonv can we get this out soonish? :)

**Comment by kentonv** [comment]
Sorry, pinging me via @-mention on github doesn't work; I get a deluge of such pings and can't keep up with them. You need to ping me by IMing me or in-person if immediate action is required.

I guess now the date on this post needs to be changed. Sorry about that.

**Comment by neynah** [comment]
Updated to February 25!

**Pull request merged**
