### PR TITLE
Add GitWeb Pages to the app list

### PR DESCRIPTION
**Pull request by oshepherd**
As the title says

cc: @paulproteus

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
You might want to update the date @oshepherd because it looks like you copied it from the Gitweb release.

**Comment by kentonv** [comment]
I'll fix it. Thanks!

**Comment by kentonv** [comment]
Hey Owen, I'm really excited about this app but it looks like right now the front page (of the app) lacks instructions on how exactly to publish a site with it. Asheesh mentions that instructions show up when "git push"ing. Do you think you could edit the front-page text to also describe things there, since otherwise users may not get that far?

**Comment by paulproteus** [comment]
Hey @kentonv , has this been deployed? I don't see it at https://sandstorm.io/apps/

**Comment by ocdtrekkie** [comment]
@paulproteus https://github.com/sandstorm-io/sandstorm-website/commit/543173042141ec7a5bdef011fe6c2a05c6dc0026

**Comment by paulproteus** [comment]
Thanks @ocdtrekkie​ !

**Comment by kentonv** [comment]
I was hoping @oshepherd would address my comment, and then we'd make it live.

**Comment by oshepherd** [comment]
I totally forgot to add that to my to-do list

**Pull request merged**
