### PR TITLE
Split /get into 2 pages, In-app Billing graphic

### PR DESCRIPTION
**Pull request by neynah**
Ready to merge but code needs cleanup. Similar to /features, there are 2 subpage tabs for Oasis Hosting and Run your Own.

### CODE REVIEW

**Comment by kentonv** [comment]
Hmm, I thought we had decided that it should remain one page, but needed two big click targets at the top for "managed hosting" vs "self hosting" which would scroll down to the appropriate section. We'd then have "sign up" and "download" links in the topbar that lead to the two sections of the page.

**Comment by kentonv** [comment]
It looks like this change is a superset of that so let me see if I can pull out the right bits.

**Comment by neynah** [comment]
get-redesign2

**Comment by kentonv** [comment]
Implemented!

**Pull request closed without merging**
