### PR TITLE
Say it is a productivity suite

### PR DESCRIPTION
**Pull request by paulproteus**
Refs https://github.com/sandstorm-io/sandstorm/issues/2545

### CODE REVIEW

**Comment by paulproteus** [comment]
The following screenshot has the before (on the right) and after (on the left).

screenshot from 2016-09-13 19 05 03

**Comment by paulproteus** [comment]
@neynah requesting your +1/-1.

Once I get that, I'll request a review/merge by @kentonv.

**Comment by neynah** [comment]
I think reduce the top margin on "Sign up for free" button to about 30px and it'll be good.

**Comment by paulproteus** [comment]
OK, decreased m argin to 30px.

You can see that I did so here:

screenshot from 2016-09-13 19 39 41

You can see a comparison with the original page here:

screenshot from 2016-09-13 19 39 54

**Comment by paulproteus** [comment]
@neynah re-requesting your +1/-1 whenever you can.

**Comment by neynah** [comment]
+1!

**Comment by paulproteus** [comment]
Great! @kentonv ready for your review/merge.

**Pull request merged**
