### PR TITLE
Handle demo correctly, and change buttons to "Try Demo" when appropriate

### PR DESCRIPTION
**Pull request by jparyani**
Fixes https://github.com/sandstorm-io/sandstorm/issues/292

### CODE REVIEW

**Comment by kentonv** [comment]
Hmm, if someone arrived at the app list by actually clicking "install apps" on demo.sandstorm.io, I don't think we want to add the interstitial. So I don't think you want to special-case `?host=https://demo.sandstorm.io` here. We only want to change the case where no host was provided. Meanwhile, we should change the installation route in Sandstorm itself to detect when the user isn't logged in but demo accounts are enabled and redirect to /appdemo in that case. Or I suppose we could _just_ do the latter and then only change the app list such that if no host is specified, demo is chosen by default...

**Comment by jparyani** [comment]
Removed the special case on `host=https://demo.sandstorm.io`. Fixing Sandstorm for non logged in users that received a link with `?host=https://demo.sandstorm.io` will have to be fixed in the shell.

**Comment by kentonv** [comment]
Hmm, how about we get rid of the radio buttons entirely? If you go to /apps without a parameter, you only get the option to try demos (via /appdemo). Should simplify the code a lot. Also, the buttons labels should probably change to "Try Demo >>" in this case.

**Comment by ocdtrekkie** [comment]
I often navigate directly to the app list, @kentonv, hit an install button, fail, and then go up and click the Alpha bubble, and then try again. I'd hate to assume that I have to come from my Sandstorm instance to use the app list.

**Comment by kentonv** [comment]
@ocdtrekkie Hmm. But this favors our hosting over self-hosting.

I guess the ideal solution would be for us to remember what servers you have access to, perhaps via a cookie. So once you've clicked "install apps" from your server once, you will always be presented with that server as an option in the future...

(Though for demo.sandstorm.io, this knowledge should expire after an hour.)

**Comment by ocdtrekkie** [comment]
I don't know if it's "favoring" to recognize that you are probably getting more traffic to/from your own servers, and can't identify every other Sandstorm server out there. And especially since this is all temporary pending the app store being done.

I mean, eventually, if your store has paid things, then you're signed into an account, and your account can specify the Sandstorm servers you use, and which one you default want to install to. But for now, I think the radio buttons serve their purpose.

I will say that if the buttons say 'Try Demo' when no server is selected, and change to saying 'Install' when a button is selected, I will probably notice that, and go up and click a radio button before I press Install. Whereas currently I have to fail before I realize I need to do that first.

**Comment by jparyani** [comment]
Fixed

**Pull request merged**
