### PR TITLE
Education landing page

### PR DESCRIPTION
**Pull request by neynah**
Is actually #175. My repo had a fatal: loose object.

### CODE REVIEW

**Comment by kentonv** [comment]
This is great! Only problem is that both of the "Start Sandstorm setup" buttons still go to the QuickSurvey. They should instead link to "/get-feature-key" or "/install" (not sure which we decided to go with).

Also let me know explicitly when you're ready to have this published. (Not sure if you're still waiting for feedback from others.)

**Comment by neynah** [comment]
Looks like Iost that change while I was trying to recover my commit. :) Fixed now. I already got +1st from Asheesh & Jade.

Thanks for the review!

**Comment by paulproteus** [comment]
+1 I'm excited to see this go out

**Comment by kentonv** [comment]
@neynah Hmm, possible bug: If the screen is wide enough, Grand Potter's photo ends up overlapping the blue band below it ever-so-slightly. May want to put a min-height on that section.

(I only noticed this after making the page live. So, it's live now.)

**Comment by kentonv** [comment]
Relatedly, the paragraph under his quote (starting with "The BC Open Educational ..." wraps kind of funny at smaller widths.

**Comment by neynah** [comment]
Hmm. It doesn't look right. I'll PR a fix tonight.

**Pull request merged**
