### PR TITLE
Removes Google Fonts (UNTESTED)

### LINKED ISSUE #199: Move fonts to sandstorm.io hosting.
I suggest that for image purposes, it's ideal if Sandstorm.io's website isn't loading resources unnecessarily from Google. It should be trivial to switch to having the fonts stored with the website.

privacybadger

### PR DESCRIPTION
**Pull request by ocdtrekkie**
Essentially what I did here is take the CSS imported from Google Fonts, strip it back to just Latin. I also needed to add woffs you use but didn't have hosted.

Sidenote on woffs: Using latest ttf-woffs from Adobe's releases here, they are likely newer "versions" than your other woffs. Also apparently woff2 is a thing, but I stuck with using woff, because your existing fonts hosted here were woff.

Fixes #199

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
Assuming this PR checks out, I'll want to add PRs to remove Google Fonts elsewhere it appears, such as the CLA, the old app list, and the main app market. My impression is the smart call is to reference https://sandstorm.io/fonts explicitly for all of them, including the app market, as the likelihood of Sandstorm folks visiting multiple Sandstorm sites is high, and we benefit from browser caching that way.

**Comment by ocdtrekkie** [comment]
I read about WOFF2 and apparently a 30% compression gain on average is a thing: https://gist.github.com/sergejmueller/cf6b4f2133bcb3e2f64a

So I guess, assuming this PR checks out, I'd like to add woff2 with woff as the fallback, in order to minimize the performance impact. And probably at that point just update the old woff files to the newest version too.

...And maybe we should make a separate CSS file for the fonts so it can be imported it the same way it was for Google Fonts. Because that will make it easier/cleaner for the other places Google Fonts should be removed.

**Comment by kentonv** [comment]
IIRC different browsers have very different preferences regarding font formats. There's woff, woff2, svg (yes, as a font), eot, ttf, ... I think the Google servers serve different css depending on your user-agent.

But that was a few years ago. Is woff widely-enough supported these days that you can get away with it alone?

**Comment by ocdtrekkie** [comment]
WOFF: https://caniuse.com/#search=woff
WOFF2: https://caniuse.com/#search=woff2

So I think we can get away with "just woff", but we should do "woff2 + woff" because woff2 is better compressed.

I retrieved the URL of `@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300italic,400,600);` as the code I imported, so my guess is either Google Fonts is only delivering woff2 or Google Fonts checks which browser makes the request, I guess...

(I think this is a DON'T MERGE PR at this point, by the way, I'm thinking about a separate CSS file.)

**Pull request closed without merging**
