### PR TITLE
Ubuntu 16.04 LTS in install docs

### PR DESCRIPTION
**Pull request by mrdomino**
cc @paulproteus

### CODE REVIEW

**Comment by paulproteus** [comment]
Hi @mrdomino !

I guess before I +1 this, I should add an `installer-tests/` test in the main Sandstorm repo that tests on Ubuntu 16.04.

I'm about to go on vacation for a few weeks, so it might take mew a few weeks, but once I have that, I'l merge this. Thanks for filing it!

**Comment by paulproteus** [comment]
I just wanted to leave a comment saying I haven't done this yet.

**Comment by twotwenty** [comment]
but how about now ?

**Comment by ocdtrekkie** [comment]
In the light that now 18.04 is the current LTS, I am starting to think this should just say "64-bit Ubuntu virtual machine". Sandstorm has not yet, AFAIK, broken on newer versions of Ubuntu, and it's unlikely that someone will try to install Sandstorm on a 6+ year old version of Ubuntu.

**Pull request closed without merging**
